use gpui::Hsla;

#[derive(Debug, Clone, PartialEq)]
pub struct StatusColors {
    pub conflict: Hsla,
    pub conflict_background: Hsla,
    pub conflict_border: Hsla,
    pub created: Hsla,
    pub created_background: Hsla,
    pub created_border: Hsla,
    pub deleted: Hsla,
    pub deleted_background: Hsla,
    pub deleted_border: Hsla,
    pub error: Hsla,
    pub error_background: Hsla,
    pub error_border: Hsla,
    pub hidden: Hsla,
    pub hidden_background: Hsla,
    pub hidden_border: Hsla,
    pub hint: Hsla,
    pub hint_background: Hsla,
    pub hint_border: Hsla,
    pub ignored: Hsla,
    pub ignored_background: Hsla,
    pub ignored_border: Hsla,
    pub info: Hsla,
    pub info_background: Hsla,
    pub info_border: Hsla,
    pub modified: Hsla,
    pub modified_background: Hsla,
    pub modified_border: Hsla,
    pub predictive: Hsla,
    pub predictive_background: Hsla,
    pub predictive_border: Hsla,
    pub renamed: Hsla,
    pub renamed_background: Hsla,
    pub renamed_border: Hsla,
    pub success: Hsla,
    pub success_background: Hsla,
    pub success_border: Hsla,
    pub unreachable: Hsla,
    pub unreachable_background: Hsla,
    pub unreachable_border: Hsla,
    pub warning: Hsla,
    pub warning_background: Hsla,
    pub warning_border: Hsla,
}

fn hex(s: &str) -> Hsla {
    let rgba = gpui::Rgba::try_from(s).expect("invalid hex color");
    rgba.into()
}

impl StatusColors {
    pub fn dark() -> Self {
        Self {
            conflict: hex("#f07178"),
            conflict_background: hex("#48161b"),
            conflict_border: hex("#66272d"),
            created: hex("#aad84c"),
            created_background: hex("#294113"),
            created_border: hex("#405c1c"),
            deleted: hex("#f07178"),
            deleted_background: hex("#48161b"),
            deleted_border: hex("#66272d"),
            error: hex("#f07178"),
            error_background: hex("#48161b"),
            error_border: hex("#66272d"),
            hidden: hex("#696a6a"),
            hidden_background: hex("#313337"),
            hidden_border: hex("#383a3e"),
            hint: hex("#628b80"),
            hint_background: hex("#0d2f4e"),
            hint_border: hex("#1b4a6e"),
            ignored: hex("#696a6a"),
            ignored_background: hex("#313337"),
            ignored_border: hex("#3f4043"),
            info: hex("#5ac1fe"),
            info_background: hex("#0d2f4e"),
            info_border: hex("#1b4a6e"),
            modified: hex("#feb454"),
            modified_background: hex("#572815"),
            modified_border: hex("#754221"),
            predictive: hex("#5a728b"),
            predictive_background: hex("#294113"),
            predictive_border: hex("#405c1c"),
            renamed: hex("#5ac1fe"),
            renamed_background: hex("#0d2f4e"),
            renamed_border: hex("#1b4a6e"),
            success: hex("#aad84c"),
            success_background: hex("#294113"),
            success_border: hex("#405c1c"),
            unreachable: hex("#8a8986"),
            unreachable_background: hex("#313337"),
            unreachable_border: hex("#3f4043"),
            warning: hex("#feb454"),
            warning_background: hex("#572815"),
            warning_border: hex("#754221"),
        }
    }

    pub fn light() -> Self {
        Self {
            conflict: hex("#ef7271"),
            conflict_background: hex("#ffe3e1"),
            conflict_border: hex("#ffcdca"),
            created: hex("#85b304"),
            created_background: hex("#e9efd2"),
            created_border: hex("#d7e3ae"),
            deleted: hex("#ef7271"),
            deleted_background: hex("#ffe3e1"),
            deleted_border: hex("#ffcdca"),
            error: hex("#ef7271"),
            error_background: hex("#ffe3e1"),
            error_border: hex("#ffcdca"),
            hidden: hex("#a9acae"),
            hidden_background: hex("#dcddde"),
            hidden_border: hex("#d5d6d8"),
            hint: hex("#8ca7c2"),
            hint_background: hex("#deebfa"),
            hint_border: hex("#c4daf6"),
            ignored: hex("#a9acae"),
            ignored_background: hex("#dcddde"),
            ignored_border: hex("#cfd1d2"),
            info: hex("#3b9ee5"),
            info_background: hex("#deebfa"),
            info_border: hex("#c4daf6"),
            modified: hex("#f1ad49"),
            modified_background: hex("#ffeeda"),
            modified_border: hex("#ffe1be"),
            predictive: hex("#9eb9d3"),
            predictive_background: hex("#e9efd2"),
            predictive_border: hex("#d7e3ae"),
            renamed: hex("#3b9ee5"),
            renamed_background: hex("#deebfa"),
            renamed_border: hex("#c4daf6"),
            success: hex("#85b304"),
            success_background: hex("#e9efd2"),
            success_border: hex("#d7e3ae"),
            unreachable: hex("#8b8e92"),
            unreachable_background: hex("#dcddde"),
            unreachable_border: hex("#cfd1d2"),
            warning: hex("#f1ad49"),
            warning_background: hex("#ffeeda"),
            warning_border: hex("#ffe1be"),
        }
    }
}
